function accexp51user25 = importdata(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ACCEXP51USER25 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ACCEXP51USER25 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  accexp51user25 = importfile("C:\Users\User\Desktop\Projeto ATD\Dados\acc_exp51_user25.txt", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 08-May-2020 11:44:59

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [1, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 3);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["AAC_X", "AAC_Y", "AAC_Z"];
opts.VariableTypes = ["double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Import the data
accexp51user25 = readtable(filename, opts);

end